jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Write to the Workspace
      run: |
        echo "This will be saved in the workspace" > "${GITHUB_WORKSPACE}/my_file.txt"
    - name: Display saved file
      run: cat "${GITHUB_WORKSPACE}/my_file.txt"
